app/show/forms.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'
__blog__ = 'http://www.os373.cn'

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError


class LoginForm(FlaskForm):
    name = StringField(u'用户名', validators=[DataRequired()])
    password = PasswordField(u'密码', validators=[DataRequired()])
    remember_me = BooleanField(label=u'记住我', default=False)
    submit = SubmitField(u'登 录')


class SearchForm(FlaskForm):
    name = StringField(u'使用员工')
    phone = StringField(u'手机号')
    start_time = StringField(u'开始时间',  validators=[DataRequired()])
    end_time = StringField(u'结束时间',  validators=[DataRequired()])
    submit = SubmitField(u'搜 索')

app/show/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'
__blog__ = u'http://www.os373.cn'


from flask import Blueprint


show = Blueprint('show', __name__, static_folder='static')

# 在末尾导入相关模块，是为了避免循环导入依赖，因为在下面的模块中还要导入蓝本main
from . import views, forms

app/show/views.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'
__blog__ = 'http://www.os373.cn'

from .. import db
from . import show
from .forms import LoginForm, SearchForm
from flask import render_template, abort, redirect, request, current_app, url_for, flash, json, jsonify
from flask_login import login_required, login_user, logout_user, current_user
from ..models import OusiStaff, OusiGuest, AlchemyJsonEncoder
from sqlalchemy import func, and_, or_
from sqlalchemy.orm import aliased
from datetime import date
import os
from collections import OrderedDict
from config import basedir
from pyexcel_xls import save_data, get_data


@show.route('/', methods = ['GET', 'POST'])
@show.route('/index', methods = ['GET', 'POST'])
@login_required
def index():

    return render_template('show/index.html')


@show.route('/login', methods = ['GET', 'POST'])
def login():
    login_form = LoginForm(prefix='login')
    if login_form.validate_on_submit():
        u = OusiStaff.query.filter_by(name=login_form.name.data.strip()).first()
        if u is None:
            flash({'error': u'用户名未注册！'})
        elif u and u.verify_password(login_form.password.data.strip()):
            login_user(user=u, remember=login_form.remember_me.data)
            return  redirect(request.args.get('next') or url_for('show.index'))
        elif u and not u.verify_password(login_form.password.data.strip()):
            flash({'error': u'密码错误！'})
        else:
            abort(403)

    return render_template('show/login.html', loginForm=login_form)


@show.route('/01', methods = ['GET', 'POST'])
@login_required
def _01():
    search_form = SearchForm(prefix='search')
    g1 = aliased(OusiGuest)
    g2 = aliased(OusiGuest)
    page = request.args.get('page', 1, type=int)
    if current_user.role == 'admin':
        database = db.session.query(OusiStaff.department, OusiStaff.name.label('staff_name'), OusiStaff.phone,
                                    OusiStaff.role,
                                    g1.name.label('guest_name'), g1.month, g1.balance,
                                    func.nvl(db.session.query(g2.balance).filter(
                                        g1.name==g2.name,
                                        func.to_date(g2.month, 'yyyy-mm')==func.add_months(
                                            func.to_date(g1.month, 'yyyy-mm'), -1)
                                    ), 0).label('last_balance')
                                    ).filter(
            OusiStaff.phone==g1.staff_phone, current_user.department==OusiStaff.department,
            g1.month==date.today().strftime('%Y-%m')
        ).order_by(g1.name).group_by(OusiStaff.department, OusiStaff.name.label('staff_name'), OusiStaff.phone,
                                     OusiStaff.role,
                                     g1.name.label('guest_name'), g1.month, g1.balance)
        if search_form.validate_on_submit():
            database = db.session.query(OusiStaff.department, OusiStaff.name.label('staff_name'), OusiStaff.phone,
                                        OusiStaff.role,
                                        g1.name.label('guest_name'), g1.month, g1.balance,
                                        func.nvl(db.session.query(g2.balance).filter(
                                            g1.name==g2.name,
                                            func.to_date(g2.month, 'yyyy-mm')==func.add_months(
                                                func.to_date(g1.month, 'yyyy-mm'), -1)
                                        ), 0).label('last_balance')
                                        ).filter(
                OusiStaff.phone == g1.staff_phone, current_user.department==OusiStaff.department,
                and_(g1.month.between(search_form.start_time.data.strip(), search_form.end_time.data.strip()),
                     OusiStaff.name.like('%{}%'.format(search_form.name.data.strip())),
                     OusiStaff.phone.like('%{}%'.format(search_form.phone.data.strip())))
            ).order_by(g1.name).group_by(OusiStaff.department, OusiStaff.name.label('staff_name'), OusiStaff.phone,
                                         OusiStaff.role,
                                         g1.name.label('guest_name'), g1.month, g1.balance)
    else:
        database = db.session.query(OusiStaff.department, OusiStaff.name.label('staff_name'), OusiStaff.phone,
                                    OusiStaff.role,
                                    g1.name.label('guest_name'), g1.month, g1.balance,
                                    func.nvl(db.session.query(g2.balance).filter(
                                        g1.name==g2.name,
                                        func.to_date(g2.month, 'yyyy-mm')==func.add_months(
                                            func.to_date(g1.month, 'yyyy-mm'), -1)
                                    ), 0).label('last_balance')
                                    ).filter(
            OusiStaff.phone==g1.staff_phone, current_user.phone==g1.staff_phone,
            g1.month==date.today().strftime('%Y-%m')
            ).order_by(g1.name).group_by(OusiStaff.department, OusiStaff.name.label('staff_name'), OusiStaff.phone,
                                    OusiStaff.role,
                                    g1.name.label('guest_name'), g1.month, g1.balance)
        if search_form.validate_on_submit():
            database = db.session.query(OusiStaff.department, OusiStaff.name.label('staff_name'), OusiStaff.phone,
                                        OusiStaff.role,
                                        g1.name.label('guest_name'), g1.month, g1.balance,
                                        func.nvl(db.session.query(g2.balance).filter(
                                            g1.name == g2.name,
                                            func.to_date(g2.month, 'yyyy-mm') == func.add_months(
                                                func.to_date(g1.month, 'yyyy-mm'), -1)
                                        ), 0).label('last_balance')
                                        ).filter(
                OusiStaff.phone == g1.staff_phone, current_user.phone == OusiStaff.phone,
                g1.month.between(search_form.start_time.data.strip(), search_form.end_time.data.strip())
            ).order_by(g1.name).group_by(OusiStaff.department, OusiStaff.name.label('staff_name'), OusiStaff.phone,
                                         OusiStaff.role,
                                         g1.name.label('guest_name'), g1.month, g1.balance)
    data = database.paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)

    return render_template('show/01.html', data=data, searchForm=search_form, database=json.dumps(database, cls=AlchemyJsonEncoder))


@show.route('/02', methods = ['GET', 'POST'])
@login_required
def _02():
    search_form = SearchForm(prefix='search')
    page = request.args.get('page', 1, type=int)
    g1 = aliased(OusiGuest)
    g2 = aliased(OusiGuest)
    if current_user.role == 'admin':
        sbq = db.session.query(OusiStaff.department, OusiStaff.role, OusiStaff.name.label('staff_name'),
                               g1.staff_phone, g1.name.label('guest_name'), g1.month, g1.balance,
                               func.nvl(db.session.query(g2.balance).filter(
                                   g1.name==g2.name,
                                   func.add_months(func.to_date(g1.month, 'yyyy-mm'), -1) == func.to_date(g2.month,
                                                                                                          'yyyy-mm')
                                                                             ), 0).label('last_balance')).filter(
            OusiStaff.phone==g1.staff_phone,
            OusiStaff.department==current_user.department
        ).group_by(OusiStaff.department, OusiStaff.role, OusiStaff.name.label('staff_name'),
                               g1.staff_phone, g1.name.label('guest_name'), g1.month, g1.balance).subquery()
        database = db.session.query(sbq.c.department, sbq.c.role, sbq.c.staff_name, sbq.c.staff_phone,
                                    sbq.c.month, func.count(sbq.c.guest_name).label('members'),
                                    func.sum(sbq.c.balance).label('balance'), func.sum(sbq.c.last_balance).label('last_balance')).\
            filter(sbq.c.month==date.today().strftime('%Y-%m')).group_by(sbq.c.department, sbq.c.role,
                                                                         sbq.c.staff_name, sbq.c.staff_phone,
                                                                         sbq.c.month)
        if search_form.validate_on_submit():
            database = db.session.query(sbq.c.department, sbq.c.role, sbq.c.staff_name, sbq.c.staff_phone,
                                        sbq.c.month, func.count(sbq.c.guest_name).label('members'),
                                        func.sum(sbq.c.balance).label('balance'),
                                        func.sum(sbq.c.last_balance).label('last_balance')). \
                filter(and_(sbq.c.month.between(search_form.start_time.data.strip(), search_form.end_time.data.strip()),
                            sbq.c.staff_name.like('%{}%'.format(search_form.name.data.strip())),
                            sbq.c.staff_phone.like('%{}%'.format(search_form.phone.data.strip())))
                       ).group_by(sbq.c.department, sbq.c.role,
                                                                               sbq.c.staff_name, sbq.c.staff_phone,
                                                                               sbq.c.month)
    else:
        sbq = db.session.query(OusiStaff.department, OusiStaff.role, OusiStaff.name.label('staff_name'),

app/templates/show/common/alert.html
<!-- flash提示 -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                {% if message['success'] %}
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>成功:</strong> {{ message['success'] }}
                    </div>
                {% elif message['error'] %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>错误：</strong> {{ message['error'] }}
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
<!-- flash提示 end -->

app/templates/show/common/base.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="{% block desc %}谦卑并倔强的活着！{% endblock %}">
        <meta name="author" content="">
        <link rel="icon" href="{{ url_for('show.static', filename='images/favicon.ico')}}">

        <title>{% block title %}报表系统{% endblock %}</title>
        {% block css %}
            <!-- 新 Bootstrap 核心 CSS 文件 -->
            <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">

            <!-- 可选的Bootstrap主题文件（一般不用引入） -->
            <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
            <link href="{{ url_for('show.static', filename='css/dashboard.css')}}" rel="stylesheet">
        {% endblock %}

        {% block js %}
            <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
            <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>

            <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
            <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

            <script src="{{ url_for('show.static', filename='js/actived.js')}}"></script>
        {% endblock %}
    </head>

    <body>
        {% include 'show/common/header.html' %}
        <div class="container-fluid">
            <div class="row">
                {% include 'show/common/sidebar.html' %}
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <div><a class="btn btn-xs btn-primary" id="toggle_sidebar">隐藏</a></div>
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

app/templates/show/common/header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">flask_oracle 项目 DEMO</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a>{{ current_user.role }}</a></li>
                <li><a> {{ current_user.name }}</a></li>
                <li><a href="{{ url_for('show.logout') }}"> 退出</a></li>
            </ul>
        </div>
    </div>
</nav>

app/templates/show/common/sidebar.html
<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        <li><a href="{{ url_for('show.index') }}"> 首页 <span class="sr-only">(current)</span></a></li>
        <li><a href="{{ url_for('show._01') }}"> 第一页 </a></li>
        <li><a href="{{ url_for('show._02') }}"> 第二页 </a></li>
    </ul>
</div>